(function() {var implementors = {};
implementors['event_loop'] = ["<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/marker/trait.Sized.html' title='core::marker::Sized'>Sized</a> for <a class='struct' href='event_loop/struct.ShouldClose.html' title='event_loop::ShouldClose'>ShouldClose</a>","<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/marker/trait.Sized.html' title='core::marker::Sized'>Sized</a> for <a class='struct' href='event_loop/struct.Size.html' title='event_loop::Size'>Size</a>","<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/marker/trait.Sized.html' title='core::marker::Sized'>Sized</a> for <a class='struct' href='event_loop/struct.SwapBuffers.html' title='event_loop::SwapBuffers'>SwapBuffers</a>","<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/marker/trait.Sized.html' title='core::marker::Sized'>Sized</a> for <a class='struct' href='event_loop/struct.PollEvent.html' title='event_loop::PollEvent'>PollEvent</a>",];
implementors['event'] = ["<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/marker/trait.Sized.html' title='core::marker::Sized'>Sized</a> for <a class='struct' href='event/events/struct.ShouldClose.html' title='event::events::ShouldClose'>ShouldClose</a>","<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/marker/trait.Sized.html' title='core::marker::Sized'>Sized</a> for <a class='struct' href='event/events/struct.Size.html' title='event::events::Size'>Size</a>","<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/marker/trait.Sized.html' title='core::marker::Sized'>Sized</a> for <a class='struct' href='event/events/struct.SwapBuffers.html' title='event::events::SwapBuffers'>SwapBuffers</a>","<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/marker/trait.Sized.html' title='core::marker::Sized'>Sized</a> for <a class='struct' href='event/events/struct.PollEvent.html' title='event::events::PollEvent'>PollEvent</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
