(function() {var implementors = {};
implementors['quack'] = [];
implementors['window'] = ["<a class='stability Unmarked' title='No stability level'></a>impl <a class='trait' href='quack/trait.ActOn.html' title='quack::ActOn'>ActOn</a>&lt;<a href='http://doc.rust-lang.org/nightly/std/primitive.tuple.html'>()</a>&gt; for <a href='http://doc.rust-lang.org/nightly/std/primitive.tuple.html'>(<a class='struct' href='event_loop/struct.SwapBuffers.html' title='event_loop::SwapBuffers'>SwapBuffers</a>, <a class='struct' href='window/struct.NoWindow.html' title='window::NoWindow'>NoWindow</a>)</a>","<a class='stability Unmarked' title='No stability level'></a>impl <a class='trait' href='quack/trait.ActOn.html' title='quack::ActOn'>ActOn</a>&lt;<a class='enum' href='http://doc.rust-lang.org/nightly/core/option/enum.Option.html' title='core::option::Option'>Option</a>&lt;<a class='enum' href='input/enum.Input.html' title='input::Input'>Input</a>&gt;&gt; for <a href='http://doc.rust-lang.org/nightly/std/primitive.tuple.html'>(<a class='struct' href='event_loop/struct.PollEvent.html' title='event_loop::PollEvent'>PollEvent</a>, <a class='struct' href='window/struct.NoWindow.html' title='window::NoWindow'>NoWindow</a>)</a>",];
implementors['sdl2_window'] = ["<a class='stability Unmarked' title='No stability level'></a>impl <a class='trait' href='quack/trait.ActOn.html' title='quack::ActOn'>ActOn</a>&lt;<a href='http://doc.rust-lang.org/nightly/std/primitive.tuple.html'>()</a>&gt; for <a href='http://doc.rust-lang.org/nightly/std/primitive.tuple.html'>(<a class='struct' href='event_loop/struct.SwapBuffers.html' title='event_loop::SwapBuffers'>SwapBuffers</a>, <a class='struct' href='sdl2_window/struct.Sdl2Window.html' title='sdl2_window::Sdl2Window'>Sdl2Window</a>)</a>","<a class='stability Unmarked' title='No stability level'></a>impl <a class='trait' href='quack/trait.ActOn.html' title='quack::ActOn'>ActOn</a>&lt;<a class='enum' href='http://doc.rust-lang.org/nightly/core/option/enum.Option.html' title='core::option::Option'>Option</a>&lt;<a class='enum' href='input/enum.Input.html' title='input::Input'>Input</a>&gt;&gt; for <a href='http://doc.rust-lang.org/nightly/std/primitive.tuple.html'>(<a class='struct' href='event_loop/struct.PollEvent.html' title='event_loop::PollEvent'>PollEvent</a>, <a class='struct' href='sdl2_window/struct.Sdl2Window.html' title='sdl2_window::Sdl2Window'>Sdl2Window</a>)</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
